name: Staging Deployment
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Allow /app as a safe Git directory
        run: git config --global --add safe.directory /app

      - name: Install laravel envoy
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs
          command: require laravel/envoy --dev

      - name: Adding Staging server key
        run: |
          echo "${{ secrets.DEV_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "144.126.254.193" > ~/.ssh/known_hosts
      - name: Deploying to Staging server
        run: ./vendor/bin/envoy run deploy
